### ISSUE TITLE
Can't not get it past these Markbot things

### ISSUE THREAD

**Issue by jenn-sweet** [jenn-sweet/web-design-2-independent-project#2]
@thatkidmadrid
Keep getting this from Markbot and no idea how to fix it.
The hover error sucks too cause I did a transition and it won't recognize it
<img width="570" alt="Screen Shot 2021-12-07 at 9 05 59 PM" src="https://user-images.githubusercontent.com/77341921/145135892-0fa217e5-fb17-4faa-8597-b7bf8a6a7838.png">
.

**Comment by thatkidmadrid** [comment]
- is this the latest error message you're getting? I see skip links as the first element in your body
- you need to give your anvigation the id `nav` like `<nav id="nav" role="navigation">` so your skip link has somewhere to go. The same comment for your main
- try moving your banner into your main and using another wrapper to contain what's currently in main. Like Markbot says, all your conetent should be contained by landmarks. the `<main role="main">` should meet this requirements
- You are missing hover/focus styling in your navigation links
