### ISSUE TITLE
Website Testing

### ISSUE THREAD

**Issue by seguinryan** [jenn-sweet/web-design-2-independent-project#3]
Hi Jenn!

Your website is looking great, really abstract, strong use of fonts and colours, and navigation is practically seamless. Also — my girlfriend loved your site, too. She'd like to adopt a marshmallow! Hope this critique helps! – Ryan

Issue #1: Buttons
• On the home page, there are two navigational buttons on the top of the webpage. "skip to navigation" and "skip to main". These buttons on the site don't seem to currently have a function, or perhaps the actions that are supposed to follow cannot be seen. I would suggest you just remove these buttons entirely, because your site is already very functional.

Issue #2: Adopting a Marshmallow
• After choosing to adopt a marshmallow, maybe set up an adoption page / website forum? You must be on this part currently, but maybe like when you add your payment information to a website, instead of choosing directly on the site as you have it, you can add a forum within your site and select the marshmallow colour within a drop-down menu (if possible).

**Comment by thatkidmadrid** [comment]
https://learn-the-web.algonquindesign.ca/courses/shared/browser-testing/#create-a-detailed-issue
